services:
  database:
    image: bitnami/postgresql
    container_name: task_manager_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_PASSWORD_ROOT=admin
      - POSTGRES_DB=task_manager
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
