name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5433:5432
        env:
          POSTGRESQL_USERNAME: admin
          POSTGRESQL_PASSWORD: admin
          POSTGRESQL_DATABASE: task_manager_test

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci

      - run: npm run test
