name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  run-unit-tests:
    name: Run unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5433:5432
        env:
          POSTGRESQL_USERNAME: admin
          POSTGRESQL_PASSWORD: admin
          POSTGRESQL_DATABASE: task_manager_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: "postgresql://admin:admin@localhost:5433/task_manager_test?schema=public"

      - name: Run Tests
        run: npm run test:e2e
